### ISSUE TITLE
There was a bug in meshsegnet.py. Please fork again!

### ISSUE THREAD

**Issue by Tai-Hsien** [Tai-Hsien/MeshSegNet#1]
For whom forked the repo before 6/24/2020.

There was a bug in meshsegnet.py. I have fixed it and updated. Feel free to forked it again! Thanks!

**Comment by MrCrazyCrab** [comment]
@Tai-Hsien `if __name__ == '__main__':
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model = MeshSegNet().to(device)
    summary(model, [(15, 6000), (6000, 6000), (6000, 6000)])`
i think there is still a bug in here.

**Comment by Tai-Hsien** [comment]
> @Tai-Hsien `if __name__ == '__main__': device = torch.device('cuda' if torch.cuda.is_available() else 'cpu') model = MeshSegNet().to(device) summary(model, [(15, 6000), (6000, 6000), (6000, 6000)])`
> i think there is still a bug in here.

**Comment by Tai-Hsien** [comment]
Hello,
I think the code you post is "meshsegnet.py". I tested it again and didn't see any issue. Could you let me know what the error message is?
Also, the main code in "meshsegnet.py" is used to see the structure of the network (based on pytorch-summary, https://github.com/sksq96/pytorch-summary). When you train the network or test, the main code in "meshsegnet.py" won't be executed.
