### ISSUE TITLE
Problem when running the initial step - line 65 in mesh.applyTransform(vtk_matrix)

### ISSUE THREAD

**Issue by cogitas3d** [Tai-Hsien/MeshSegNet#11]
Hi

First of all, I would like to thank you for making this material available on GitHub.

Second, I downloaded the code, installed the necessary libraries and created two .vtp files from STLs.

When I run the step1_augmentation.py script it always asks me for an extra file, for example:

src / Sample_02_d.vtp

> ❌ Error in load(): cannot load src/Sample_02_d.vtp
Traceback (most recent call last):
  File "step1_augmentation.py", line 65, in <module>
    mesh.applyTransform(vtk_matrix)
AttributeError: 'NoneType' object has no attribute 'applyTransform'

I'm sorry for my lack of experience, but is it necessary for me to export about 36 models as you did so that the first part of the process runs smoothly?

Thank you for your attention.

**Comment by Tai-Hsien** [comment]
Hello,
It looks like that "mesh" is NoneType, which means Line 64 `mesh = load(os.path.join(vtk_path, file_name))` doesn't work correctly.
Please make sure mesh is loaded properly. Maybe check the path or filename. If you are not familiar with the problem. You can move Sample_02_d.vtp under the same folder, make `vtk_path='./'` and try it.

**Comment by Tai-Hsien** [comment]
Hello,

In your screenshot, you only have one sample and its flipped one. In this case, you need to do `num_samples=1`. However, this action is only for no error. If you plan to train a new model, you need to have more samples. It's hard to say how many is enough. More is always better. In our papers, we used 36 upper mesh models to train MeshSegNet.

In addition, we perform random transform for each sample (in your situation, there is only one sample) to augment the data. What you see in `augmentation_vtk_data` are the augmented data.

**Comment by Tai-Hsien** [comment]
Also, based on our experience, we train upper and lower cases separately to get better accuracy.

**Comment by cogitas3d** [comment]
Thank you.

I exported 6 different upper models to trainning. All works well until step4, when I received an error:

> python3 step4_test.py
Testing
Predicting Sample filename: Sample_01_d.vtp
❌ Error in load(): cannot load Sample_01_d.vtp
Traceback (most recent call last):
  File "step4_test.py", line 57, in <module>
    labels = mesh.getCellArray('Label').astype('int32').reshape(-1, 1)
AttributeError: 'NoneType' object has no attribute 'getCellArray'

**Comment by Tai-Hsien** [comment]
This the same problem as the first problem you faced. Your mesh is `NoneType`, which means that the program didn't read the vtp file properly. You might check the code where you load the vtp file.

**Comment by Tai-Hsien** [comment]
The error message is still the same, which means you haven't fixed the problem.
This is the same problem as in step 1. If you can pass step 1, you should be able to pass step 4. It should be a small mistake but you must check it carefully. Again, check your filename and path, and make sure you understand the meaning of these lines.

**Comment by cogitas3d** [comment]
I'm not familiar with the file format. Could you be so kind as to look?

[Sample_01_d.zip](https://github.com/Tai-Hsien/MeshSegNet/files/6460306/Sample_01_d.zip)

It appear works well when I open directly with vedo:
![Captura de tela_2021-05-11_11-30-27](https://user-images.githubusercontent.com/2422483/117842840-4f24c300-b24c-11eb-9c09-bac1a8f00b60.png)

I used this script to convert from STL to VTP:
https://correlated.kayako.com/article/70-stl2vtp-python-script

**Comment by Tai-Hsien** [comment]
Hello,
In step 4, we test the network's performance, so we predict the segmentation by the network, and compare the result to the ground truth. The cell array "Label" is the data of ground truth. Since your file converted from STL doesn't have the ground truth (i.e., the "label" array), `mesh.getCellArray('Label').astype('int32')` returns nothing to compare.

If you just want to see the prediction from the network, you might use step5 (without post-processing), or step6 (with post-processing).

**Comment by cogitas3d** [comment]
I use a STL file to test the step5:

[Example.zip](https://github.com/Tai-Hsien/MeshSegNet/files/6461133/Example.zip)

And returned this:

> python3 step5_predict.py 
Predicting Sample filename: Example.stl
	Downsampling...
	Predicting...
Traceback (most recent call last):
  File "step5_predict.py", line 66, in <module>
    cells[i][0], cells[i][1], cells[i][2] = mesh_d._polydata.GetPoint(mesh_d._polydata.GetCell(i).GetPointId(0)) # don't need to copy
AttributeError: 'Mesh' object has no attribute '_polydata'

I tryied with OBJ and the output was the same. I exporte from Blender and MeshLab and the output was the same.

**Comment by cogitas3d** [comment]
Thank you very much @Tai-Hsien 

Your results with Example was very impressive.

I download again the conde and:

1: Keep the value of line 20:
> mesh_path = './'  # need to define

2: Keep the model_name of line 18:
> model_name = 'MeshSegNet_Max_15_classes_72samples_lr1e-2_best.tar'

But when I run, the same error appear to me:

> python3 step5_predict.py 
Predicting Sample filename: Example.stl
	Downsampling...
	Predicting...
Traceback (most recent call last):
  File "step5_predict.py", line 67, in <module>
    cells[i][0], cells[i][1], cells[i][2] = mesh_d._polydata.GetPoint(mesh_d._polydata.GetCell(i).GetPointId(0)) # don't need to copy
AttributeError: 'Mesh' object has no attribute '_polydata'

**Comment by Tai-Hsien** [comment]
Hello,
Where is the `Example.stl`? In addition, could you `print(mesh.points().shape, mesh_d.points().shape)` right after Line 64 and let me know what the results are?

**Comment by cogitas3d** [comment]
@Tai-Hsien 

UPDATE: I made a mistake. First I used a MAN instead a MAX... now it is right (maxilla).

![Captura de tela_2021-05-11_17-47-31](https://user-images.githubusercontent.com/2422483/117889235-308cef00-b281-11eb-8470-b55ff63891c9.png)
