### ISSUE TITLE
Problem to export PLY with different colors

### ISSUE THREAD

**Issue by cogitas3d** [Tai-Hsien/MeshSegNet#12]
Hey there,

I tryied to export the result .vtp file to be imported into Blender with different colors.

Initially I export like OBJ, but the result object (without MTL file) have only one color.

So, I export like PLY and the object have only two colors, one material to teeth and other material to reaminder faces:

![Captura de tela_2021-05-12_06-49-38](https://user-images.githubusercontent.com/2422483/117974678-d7ae6c80-b2fb-11eb-824e-08a5cf2771ef.png)

I used vedo to do it, and try to use vtkplotter, with same results. When I try to export directly with VTK on Python, I had some erros aparrently because the VTK is a polidata.

So, I research on issues about the possibility to export with different material and found this: https://github.com/Tai-Hsien/MeshSegNet/issues/7

But when I made it the output was this:

> python3 step6_predict_with_post_processing_pygco.py 
Predicting Sample filename: Arcada_Inferior.stl
	Downsampling...
	Predicting...
	Refining by pygco...
	Upsampling...
Original contains too many cells, simpify to 99998 cells
Sample filename: Arcada_Inferior.stl completed
	computing time: 12.73 sec
Traceback (most recent call last):
  File "step6_predict_with_post_processing_pygco.py", line 262, in <module>
    valid_labels = np.unique(mesh2.cell_attributes['Label']).astype(np.int32) # get all valid labels
AttributeError: 'Mesh' object has no attribute 'cell_attributes'

Is it possible to export to PLY keeping the different color materials?

Thank you for your attention.

**Comment by Tai-Hsien** [comment]
Hello,
Unfortunately, we don't use PLY. We found VTK format is the most flexible format to sort high-dimensional point and cell data, which is hard to be done using the classical mesh format such as STL, OBJ, and PLY.

If you really want to do it, I suggest understanding the format of PLY and VTK/VTP, and you can write your own script to convert the mesh.

**Comment by Tai-Hsien** [comment]
FYI. If you plan to use the Blender to modify the segmentation result, another my work Mesh Labeler (https://github.com/Tai-Hsien/Mesh_Labeler) can achieve it. Hope it helps!

**Comment by cogitas3d** [comment]
@Tai-Hsien 

Thank you very much!

**Comment by cogitas3d** [comment]
@Tai-Hsien 

I get the colors exporting from vpt to ply on Paraview:

![IMG-20210512-WA0008](https://user-images.githubusercontent.com/2422483/118063199-9901cc00-b366-11eb-9532-70dab2d285cb.jpg)

But unfortunately I need a solution based on command line or Python lib, to put I in a Blender addon.

Do you think it is possible convert scalars to color material from your script? Or, separate meshes from a same lookup table?

**Comment by Tai-Hsien** [comment]
Hello,
You can look at file structure of PLY format (e.g., http://paulbourke.net/dataformats/ply/) and write a python script to convert it.

**Comment by cogitas3d** [comment]
Ready!

Now you can run MeshSegNet inside OrtogOnBlender add-on.

YouTube video:

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/Ip_gYMoFK1E/0.jpg)](https://www.youtube.com/watch?v=Ip_gYMoFK1E)

Next step: Pubblish a book chapter about it, cite the tools and mak the acknoledgements.

Thank you very much @Tai-Hsien !
