### ISSUE TITLE
Flipping vtp file

### ISSUE THREAD

**Issue by smoothumut** [Tai-Hsien/MeshSegNet#13]
Hi Tai, how can I flip a vtp file with labels? Is there any code block in your project, or is there a very simple function in vtk, or somewhere else?
Best Regards

**Comment by Tai-Hsien** [comment]
Hello,

You can take a look at the function at https://github.com/Tai-Hsien/easy_mesh_vtk/blob/ea0be0222226f2bda84069f70208ba6e4e644b40/easy_mesh_vtk.py#L571

**Comment by smoothumut** [comment]
Thanks a lot for your quick answer and support, wow, It is a great function, it is very admirable that you have thought every thing : ) 
I will let you know if I come to a problem about it.
Thanks again, Best Regards

**Comment by ananyajana** [comment]
Hi Tai Hsien,
As easy_mesh_vtk is no longer maintained, could you please let us know how to flip a mesh using vedo?

**Comment by Tai-Hsien** [comment]
@ananyajana 

I do mirror X axis to flip the mesh data. You can look at the below example.
```
mesh_f = mesh.clone(deep=True).mirror("x")
label_f = mesh_f.getCellArray('Label')
for i in range(1, 17):
    if len(label_f==i) > 0:
        label_f[label==i] = 17-i #1 -> 16, 2 -> 15, ..., 16 -> 1
write(mesh_f, 'Sample_{}_d_flip.vtp'.format(i_sample))
```

**Comment by ananyajana** [comment]
Thank you @Tai-Hsien !
