### ISSUE TITLE
Pygco error on Windows

### ISSUE THREAD

**Issue by cogitas3d** [Tai-Hsien/MeshSegNet#15]
Hey there!

I get to run MeshSegNet suscessfully on Linux, and almost in Windows. All OK with step5 but when I try to run step6 I get this error:

> Traceback (most recent call last):
  File "C:/OrtogOnBlender/MeshSegNet/./step6_predict_with_post_processing_pygco.py", line 17, in <module>
    from pygco import cut_from_graph
  File "gco_python.pyx", line 1, in init pygco
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

The las error I sent here happen because the version of vedo, I fix it thanks @Tai-Hsien that inform the right version. Could this be the same thing with pygco version problem?

Thank you for the attention.

**Comment by Tai-Hsien** [comment]
Hello,
I actually ran step6 on Windows machine and didn't get this error. Do you have more information about this error?

**Comment by cogitas3d** [comment]
I try to install pygco 0.0.1 and I had errors. So, I make this:

pip uninstall numpy
pip install numpy

And works!

Linux = OK
Windows = OK
Next system -> Mac OS X

![Captura de tela 2021-05-17 044503](https://user-images.githubusercontent.com/2422483/118483271-aa323c00-b6ca-11eb-8dbb-7b4b9ba88750.png)

**Comment by cogitas3d** [comment]
@Tai-Hsien 

I run 5 tests in upper and lower arch in a same computer with three different OS: Windows, Linux and Mac.

Lenovo Ideapad S145;
Intel Core i7-8565U 1.80GHz;
20GB RAM.

**Results**:

Table (seconds):
![Captura de tela_2021-05-26_08-12-17](https://user-images.githubusercontent.com/2422483/119658538-40690f00-bdfb-11eb-822a-da47b1854e69.png)

Chart 1:
![Captura de tela_2021-05-26_08-11-42](https://user-images.githubusercontent.com/2422483/119658597-54147580-bdfb-11eb-8dbf-d84c2f31d2fd.png)

Average:
![Captura de tela_2021-05-26_08-11-57](https://user-images.githubusercontent.com/2422483/119658624-5bd41a00-bdfb-11eb-8500-f7edb8183dc1.png)

Curiously CUDA appear do not help descrease the time, I test with and without and the time was the same on Linux.

Thank you for all!

**Comment by Tai-Hsien** [comment]
Hello @cogitas3d 
Thanks for the test! It's surprised that Linux takes the longest. Do you know the time spent for each block (i.e.., downsampling, network prediction, graph-cut, and, upsampling)?
