### ISSUE TITLE
With more GLMs can make the performance better?

### ISSUE THREAD

**Issue by zhDai** [Tai-Hsien/MeshSegNet#16]
Hi Tai,
When I read your paper and code, I find that you use two GLMs where make As<0.1 and AL<0.2. So more GLMs can make the performance better?

**Comment by Tai-Hsien** [comment]
Hello @zhDai ,
Theoretically, yes. Based on the ablation study in our paper, you can see using two GLMs get a better result.
However, in reality, it needs to try. I guess it won't improve too much.
