### ISSUE TITLE
The number of teeth to train the model

### ISSUE THREAD

**Issue by SivHMA** [Tai-Hsien/MeshSegNet#17]
If I have 16 teeth and gingiva now instead of 14, how can I modify the parameters to train the model
![image](https://user-images.githubusercontent.com/29498630/125226341-7e66b780-e303-11eb-8a48-c8f132d44fbb.png)

Thank you for the attention

**Comment by Tai-Hsien** [comment]
Hello,
I assume you already have your dataset ready. Then, you need to modify `15` to `17` for Line 26 and Line 76.
https://github.com/Tai-Hsien/MeshSegNet/blob/91bd00a3e4bfa6718441ba671d30d2a424735302/step3_training.py#L26
https://github.com/Tai-Hsien/MeshSegNet/blob/91bd00a3e4bfa6718441ba671d30d2a424735302/step3_training.py#L76

**Comment by SivHMA** [comment]
> Hello,
> I assume you already have your dataset ready. Then, you need to modify `15` to `17` for Line 26 and Line 76.
> https://github.com/Tai-Hsien/MeshSegNet/blob/91bd00a3e4bfa6718441ba671d30d2a424735302/step3_training.py#L26
> 
> 
> https://github.com/Tai-Hsien/MeshSegNet/blob/91bd00a3e4bfa6718441ba671d30d2a424735302/step3_training.py#L76
Thank you for your reply.

Just now, I tried to modify these two places, but I prompted the following error when running：

`Training model...
Traceback (most recent call last):
  File "step3_training.py", line 96, in <module>
    one_hot_labels = nn.functional.one_hot(labels[:, 0, :], num_classes=num_classes)
RuntimeError: Class values must be smaller than num_classes.`

I don't know what's wrong with me, have you ever met this situation

**Comment by Tai-Hsien** [comment]
Hello,
I believe the problem comes from your dataset because the error message says `RuntimeError: Class values must be smaller than num_classes.`
Do your subjects have a cell array called 'Label' and contains a label number from 0 to 16?

**Comment by SivHMA** [comment]
Thank you for your reply.
After checking one by one(This is a huge project), I did find a problem file. After replacement, everything was normal.
Thanks again!

**Comment by SivHMA** [comment]
There is a problem. When I try to select only 9 models and test them 4 times, there is no problem. But when I test 36 models at one time, I will report an error. `RuntimeError: Class values must be smaller than num_classes.` I'm still trying to find a solution

**Comment by Tai-Hsien** [comment]
Hello,
It's the same error message. I believe some of your intraoral models don't follow one-hot code. You may test them one by one to figure out which one contains error.

**Comment by SivHMA** [comment]
Is there any good tool to observe the problematic model more intuitively?

**Comment by Tai-Hsien** [comment]
If you're familiar with vtk or vedo, you can run a python script to check which model contains label that > 16 (if number of classes = 17).

**Comment by SivHMA** [comment]
I found a way to find the problem about it as quickly as possible. I can open the VTP file with 'Notepad++', and then I can see the maximum distance of the label at this location.
![1626337518(1)](https://user-images.githubusercontent.com/29498630/125764445-e3319ba5-3ad6-4928-83ad-cb35f7b8d2ee.jpg)

And I found the cause of the problem, I use your 'Mesh_Labeler', I tried to draw lines with the 'S' key. Coincidentally, I accidentally pressed the wrong key when drawing lines.
![1626339803(1)](https://user-images.githubusercontent.com/29498630/125764510-e9e25e29-c2a8-4ae8-b26c-f89978416c95.jpg)

To save time, I directly saved the VTP file and then reloaded it. After opening the file, I found that the color of the selected place before drawing lines was also saved. This gray grid results in a maximum distance of 27(Most of the time, these grids are not so conspicuous. They are just a few scattered grids selected by the right mouse button).
![1626339829(1)](https://user-images.githubusercontent.com/29498630/125764547-f14f23dd-3f63-4534-aafc-960686901333.jpg)

So I modify the file again, and finally, everything was OK!
Thank you for your reply!

**Comment by SivHMA** [comment]
I'm sorry for disturbing you again.
I tried to test it in the middle of machine learning. I don't know why I didn't separate label 0.
![image](https://user-images.githubusercontent.com/29498630/125900019-b94677fb-b90e-4f9b-b40e-d2bf4ae3e2f9.png)
Is there something wrong with my data set?

**Comment by Tai-Hsien** [comment]
I have no idea. Could you provide a sample in your dataset?

**Comment by SivHMA** [comment]
Could you help me to have a look?
[Sample_04_d.zip](https://github.com/Tai-Hsien/MeshSegNet/files/6828521/Sample_04_d.zip)

**Comment by Tai-Hsien** [comment]
It looks good for me.
![image](https://user-images.githubusercontent.com/9615481/125909078-b7e73beb-9717-4034-a3b8-1d0393df685d.png)

**Comment by SivHMA** [comment]
However, after being treated with pygco, there is no label 0.
[outputs.zip](https://github.com/Tai-Hsien/MeshSegNet/files/6828737/outputs.zip)
 I found that in the VTP file, the minimum value of the label is 1
![image](https://user-images.githubusercontent.com/29498630/125909926-7f551550-6a23-4e38-b3e9-9c6e86259fa8.png)

**Comment by Tai-Hsien** [comment]
I checked your output files. The gingival cells are still there, which means that the network didn't learn how to annotate gingiva.
There are several reasons. The first one is you need to make sure you feed label of 0 (i.e., gingiva) into the network when training. In your case, you have to re-train the network instead of using the pre-trained model that I upload due to different number of classes.
The other possible reason is that you don't have enough samples in your training set so the performance is quite bad. However, you should keep monitoring the training because you said the results were from a model in the middle of training. Maybe everything becomes better for longer training, because the DSC of gingiva is not considered in the loss function.

**Comment by SivHMA** [comment]
Thank you for your reply.
I think I did add the label of 0 to the network, and I'll wait and see if it gets better.
