### ISSUE TITLE
Single tooth segmentation

### ISSUE THREAD

**Issue by issamdakir** [Tai-Hsien/MeshSegNet#18]
Hi dear Tai ,
I m Dr Dakir from Morocco ...i m Dentist and i m playing a bit with python on blender i made a little addon for implant surgical guide...with possibility to record real jaw movements and transfert them to blender...in fact we are two on this project..(BDENTAL-4D) me and Dr ilya Fomenco from Ukrain.
I tryed your implemented automatic teeth segmentation very good work you did Doctor it just not 100 % consistent so i taught making a blender addon dedicated to 3d cephalometrics and orthodontic and for segmentation i wish find a robust semi autimatic workflow .
I m not familiar with ML if you can guide me in this task or better join as in the whatsapp group 
The idea is that user shoose some teeth landmarks that will be used to separate single tooth area and apply the ML part for tooth segmentation
My whatsapp 00212661058495

**Comment by Tai-Hsien** [comment]
Hello Dr. Dkir,

I have bring this information to my supervisor, Dr. Ching-Chang Ko for the potential cooperation. I believe he will contact you soon later. Meanwhile, feel free to bring the specific questions that you have here directly.

**Comment by issamdakir** [comment]
Thank you dear Bruce i ll try to prepare some images to better illustrate the idea
