### ISSUE TITLE
What's the limit of the number of meshes of the 3D model?

### ISSUE THREAD

**Issue by huizhang2017** [Tai-Hsien/MeshSegNet#2]
Hi, ...
      When the number of the meshes is large(such as > 50000, or even less), the model can not predict the result successfully, because the memory is limited(need 200GB, but only have 64GB). This is caused by two large matrix A_s and A_L in the program? How to fix this problem? 
    I think, if this problem can not be fixed, then this method can not be applied to real data which usually contains  plenty of meshes.

**Comment by Tai-Hsien** [comment]
Dear,

Thank you for being interested in our work. You are right, the two large matrices A_s and A_l are easy to cause the super huge memory issue. The similar problem also occurs in one of the post process (i.e., graph-cut refinement).

Currently, to solve this issue, we always downsample/simplify the raw mesh first, and then predict (MeshSegNet) and refine (graph-gut method) the results based on the downsampled mesh. Finally, we transfer the downsampled results back to the raw mesh using SVM or KNN. Specifically, you just need to use the downsampled mesh and its results (i.e., label on the downsampled mesh) as training set to train a SVM model, and use the model to predict the raw mesh.

Feel free to let me know if you have any further questions!

Best,

Bruce Wu

**Comment by huizhang2017** [comment]
Hi, 
    Thank you for your explanations. By the way, it seems that the link of gco-v3.0.zip is not valid any more, I can not download it, even when I use ExpressVPN. Could you please submit it in your repository? Thanks.

**Comment by huizhang2017** [comment]
> Hi,
> Thank you for your explanations. By the way, it seems that the link of gco-v3.0.zip is not valid any more, I can not download it, even when I use ExpressVPN. Could you please submit it in your repository? Thanks.

I think it can be downloaded from the following github repository " https://github.com/nsubtil/gco-v3.0 " .

**Comment by Tai-Hsien** [comment]
Hello huizhang,
I have uploaded a python script (step6) for prediction and the gco-v3.0 package. In gco-v3.0, you can see a MATLAB script (tooth_segmentation_refinement_mat.m), which is called in the "step6_predict_with_post_processing.py". The post processes in step6 script include the refinement and transfer result back to the original mesh. However, I haven't updated the README file to mention some prerequisites such as MATLAB python engine and thudersvm. I will update the README file when I have time.

**Comment by huizhang2017** [comment]
> 
> 
> Hello huizhang,
> I have uploaded a python script (step6) for prediction and the gco-v3.0 package. In gco-v3.0, you can see a MATLAB script (tooth_segmentation_refinement_mat.m), which is called in the "step6_predict_with_post_processing.py". The post processes in step6 script include the refinement and transfer of result back to the original mesh. However, I haven't updated the README file to mention some prerequisites such as MATLAB python engine and thudersvm. I will update the README file when I have time.

That's great. Thanks.
