### ISSUE TITLE
antotation tool used for mesh data(3D Intraoral Scann data)

### ISSUE THREAD

**Issue by guxss3** [Tai-Hsien/MeshSegNet#21]
Hi, thanks for your research, this repo guides me.
Could you tell me that what software I should use to annotation my own mesh data, I am new for the mesh data segmenation filed, and I wanna train my own data. I guess paraview can help me but I am not sure.

Thanks.

**Comment by Tai-Hsien** [comment]
Hello @guxss3,
Thanks for be interested in our work.
For annotation of mesh data, I suggest my other work 'Mesh Labeler' (https://github.com/Tai-Hsien/Mesh_Labeler).
Paraview is easy to render the mesh data, but is difficult if you want to modify the data.

**Comment by guxss3** [comment]
Thank you so much. @Tai-Hsien

**Comment by guxss3** [comment]
Hi, @Tai-Hsien . Sorry to bother you again.
Your work 'Mesh Labeler' is a excellent work, but the pity is that we can only pick one triangle(mesh) to annotation, which is time-consuming. And I have lots of data needed to annotation. Could you share the source code, I wanna change the function so that I can select an area once and labeling.
If the request feasible, I will share the code with you.

**Comment by Tai-Hsien** [comment]
Hello @guxss3 
Actually you can pick many triangles using "Spline mode" (which you create a spine to select triangles within the spline) in Mesh Labeler. However, sometimes the spline mode will face some issue when the spline is to aggressive.

Currently, I have deliver this request (you're not the only one to request the source code) to SOVE Inc., and it's still pending. Hope the current version of Mesh Labeler can help.
