### ISSUE TITLE
Change the internal property of vedo mesh instance

### ISSUE THREAD

**Issue by draibolit** [Tai-Hsien/MeshSegNet#22]
Accessing the internal property of Mesh class in vedo is not stable.
In my current version, I need to change "mesh_d._polydata" to "mesh_d._data".
Just let you know!

Besides, the pygco module is a a little bit tricky to install.

The segmentation is rather good. There is a much improvement in the results of the step #6 compared to step #5. Do you think more training data will improve more?

```
                # cells[i][0], cells[i][1], cells[i][2] = mesh_d._polydata.GetPoint(mesh_d._polydata.GetCell(i).GetPointId(0)) # don't need to copy
                # cells[i][3], cells[i][4], cells[i][5] = mesh_d._polydata.GetPoint(mesh_d._polydata.GetCell(i).GetPointId(1)) # don't need to copy
                # cells[i][6], cells[i][7], cells[i][8] = mesh_d._polydata.GetPoint(mesh_d._polydata.GetCell(i).GetPointId(2)) # don't need to copy
              
```

should be

```
  cells[i][0], cells[i][1], cells[i][2] = mesh_d._data.GetPoint(mesh_d._data.GetCell(i).GetPointId(0)) # don't need to copy
                cells[i][3], cells[i][4], cells[i][5] = mesh_d._data.GetPoint(mesh_d._data.GetCell(i).GetPointId(1)) # don't need to copy
                cells[i][6], cells[i][7], cells[i][8] = mesh_d._data.GetPoint(mesh_d._data.GetCell(i).GetPointId(2)) # don't need to copy


````

**Comment by Tai-Hsien** [comment]
Hello @draibolit 
Thanks for pointing this problem out. You're right. vedo updates frequently. Based on what you suggest, I believe you have already been an expert in vedo!

For your second question, more data definitely help the model be more general. However, using post-processing such as multi-label graph cut can further help!

**Comment by draibolit** [comment]
Yes, polydata() could be the good one.

In my case, the tooth # 17 has no label. I'm not sure it is because of the trained model or because of the code.

@Tai-Hsien 


![Screen Shot 2021-09-12 at 9 14 21](https://user-images.githubusercontent.com/22300298/132966638-b5c5544f-9425-4240-b7ab-ded0e0c88633.png)
![Screen Shot 2021-09-12 at 9 14 51](https://user-images.githubusercontent.com/22300298/132966641-e1841b53-e233-4865-96f6-95ad4453a0f7.png)

**Comment by Tai-Hsien** [comment]
Hello,
Our training data don't include wisdom teeth, so the current model is only for 15-class (i.e., 14 teeth + gingiva).
If you have your own training data, you can adjust the code for 17-class problem and training it.
In addition, your intraoral scan contains a base. Since our training data don't contain base, my experience is that the performance will be bad if the mesh has a base on it.

**Comment by draibolit** [comment]
Thank you very much, it is promising.
