### ISSUE TITLE
Is it possible to retrieve the downsampled predicted output with limited meshes to input with more meshes?

### ISSUE THREAD

**Issue by MianMianMeow** [Tai-Hsien/MeshSegNet#28]
Hi Bruce,
 I noticed because of the GPU memory limitation, the predicted output.vtp is downsampled to 10,000 meshes. Since my origin input.vtp has about 350,000 meshes, could you please give any short hints to create labels for the input.vtp with 350,000 meshes based on the output.vtp with 10,000 meshes. Really appreciate for you reply~

**Comment by Tai-Hsien** [comment]
Hello,

You can take a look at step6. We downsample mesh to 10,0000 cells first, then prediction, and finally use the predicted results as training data to compute KNN for projecting the segmentation mask back to the original mesh.

Best,

**Comment by MianMianMeow** [comment]
Thanks. I'm gonna check this out ; )
