### ISSUE TITLE
I'm new and i have intraoral scans are stored as obj file. 

### ISSUE THREAD

**Issue by Vaveyla95** [Tai-Hsien/MeshSegNet#29]
Hello Tai,
Thanks for your project sharing. I'm new to Mesh segmentation. You have intraoral scans are stored as VTP but I have obj file format. How can I run this project with my own data? I would appreciate if you could explain in detail. 

Thanks regards

**Comment by Tai-Hsien** [comment]
Hello @Vaveyla95 

Do you have color labeled on your OBJ files? If you prefer GUI tools, you can use my another project https://github.com/Tai-Hsien/Mesh_Labeler to do it.

If you like to do code (i.e., python), I would suggest using vedo https://vedo.embl.es/ to convert it.

Bruce Wu

**Comment by Vaveyla95** [comment]
Thank you for replying. 
Actually I have a school project about automated labeling for tooth segmentation with python. I looked at your project and liked it. I wanted to try your project with my own data set. But this is unlabeled obj file. I guess I'll convert the obj file to vtl using vedo and then follow the steps in the description, right? By the way sorry for my english. I hope you understand what I mean.

**Comment by Tai-Hsien** [comment]
Hello @Vaveyla95 

No worries. I can totally understand what you mean. It sounds like you have unlabeled data (in OBJ format). Therefore, you need to label the data first. You can use our pre-trained model to predict your own data for this part, and then refine the results using Mesh Labeler  https://github.com/Tai-Hsien/Mesh_Labeler.

What you need to do is put your obj files in to this filename list here https://github.com/Tai-Hsien/MeshSegNet/blob/b2ce6818c31170fa0cfb0951a4574a05613097b2/step6_predict_with_post_processing_pygco.py#L31

**Comment by Vaveyla95** [comment]
Okay, I understood. I'll try. Thank you. By the way, Where can I find public 3D dental model datasets labeled?

**Comment by Tai-Hsien** [comment]
Based on my understanding, there is still no public 3d dental model avaiable.

**Comment by Vaveyla95** [comment]
Hello Tai,

I modfied the code you say like 
`sample_filenames = ['/content/drive/MyDrive/tez/Data/13.12.2021-OSMAN OZDILEK-lowerjaw-obj.obj']`

I got output like this

Predicting Sample filename: /content/drive/MyDrive/tez/Data/13.12.2021-OSMAN OZDILEK-lowerjaw-obj.obj
	Downsampling...
	Predicting...
step6_predict_with_post_processing_pygco.py:107: DeprecationWarning: Call to deprecated method addCellArray. (Please use myobj.celldata[name] = myarr instead.)
  mesh_d.addCellArray(mesh_normals, 'Normal')
step6_predict_with_post_processing_pygco.py:112: DeprecationWarning: Call to deprecated method getCellArray. (Please use myobj.celldata[name] instead.)
  normals = mesh_d.getCellArray('Normal').copy() # need to copy, they use the same memory address
step6_predict_with_post_processing_pygco.py:160: DeprecationWarning: Call to deprecated method addCellArray. (Please use myobj.celldata[name] = myarr instead.)
  mesh2.addCellArray(predicted_labels_d, 'Label')
	Refining by pygco...
step6_predict_with_post_processing_pygco.py:177: DeprecationWarning: Call to deprecated method getCellArray. (Please use myobj.celldata[name] instead.)
  normals = mesh_d.getCellArray('Normal').copy() # need to copy, they use the same memory address
step6_predict_with_post_processing_pygco.py:209: DeprecationWarning: Call to deprecated method addCellArray. (Please use myobj.celldata[name] = myarr instead.)
  mesh3.addCellArray(refine_labels, 'Label')
	Upsampling...
Original contains too many cells, simpify to 99999 cells
step6_predict_with_post_processing_pygco.py:252: DeprecationWarning: Call to deprecated method addCellArray. (Please use myobj.celldata[name] = myarr instead.)
  mesh.addCellArray(fine_labels, 'Label')
Sample filename: /content/drive/MyDrive/tez/Data/13.12.2021-OSMAN OZDILEK-lowerjaw-obj.obj completed
	computing time: 36.51 sec

**Comment by Tai-Hsien** [comment]
It looks like the script has been implemented successfully. You can try to find a VTP file in the output file and see the results by either using Paraview or Mesh Labeler.

**Comment by Tai-Hsien** [comment]
There are several warning message because you probably install the latest version of vedo, which change syntax to extract the arrays.

**Comment by Vaveyla95** [comment]
![image](https://user-images.githubusercontent.com/91208636/146829879-3359d0ae-d417-4deb-9f50-7fda28278710.png)

**Comment by Tai-Hsien** [comment]
Is this lower jaw? If so, then you need to choose the pre-trained model for lower jaw. If you cannot figure it out, you can post an OBJ file here. I can take a look for troubleshooting.

**Comment by Vaveyla95** [comment]
Yes, I have the lower jaw now. Do i need to have upper jaw data segmentation performans? Actually my goal is to see the segmentation metrics.

[Uploading 13.12.2021-OSMAN OZDILEK-lowerjaw-obj.zip…]()

**Comment by Vaveyla95** [comment]
Yes, I have the lower jaw now. Do i need to have upper jaw data segmentation performans? Actually my goal is to see the segmentation metrics.

[13.12.2021-OSMAN OZDILEK-lowerjaw-obj.zip](https://github.com/Tai-Hsien/MeshSegNet/files/7748013/13.12.2021-OSMAN.OZDILEK-lowerjaw-obj.zip)

**Comment by Tai-Hsien** [comment]
Hello,
I have implemented the code, and the result is also very bad on my computer. I guess the problem is that your data is very unsimilar to our training data (however, we only have 36 training data in this project). I might try it more when I'm more available.

**Comment by Vaveyla95** [comment]
İ understood. If I gave you more datasets and trained the network on my dataset then the results would be better, right? I currently have one dataset. If I can get more data, I'll let you know. By the way, thank you very much for your time.

**Comment by Tai-Hsien** [comment]
Does your dataset labeled?

**Comment by Vaveyla95** [comment]
No

**Comment by Tai-Hsien** [comment]
This project is a supervised learning task, so only labeled dataset can be used for training.

**Comment by Vaveyla95** [comment]
You've definitely helped. Thank you for your help. I think I need to get the labeled dataset. How did you get the first figure? Did you convert the obj to vtp and then use the step6_predict_with_post_processing_pygco.pycode?

**Comment by Tai-Hsien** [comment]
Nope, step6 actually can read obj file. In the above figure, I rotated your obj file to see if we can have something different, but it didn't help much.

**Comment by Vaveyla95** [comment]
Hi Thai, it's me again :)

I have a different intraoral scanner unlabeled dataset as stl format. But I have labeled 1 dataset using your Mesh Labeler https://github.com/Tai-Hsien/Mesh_Labeler project.
As you see labeled data in the figure. Then i saved this file as vtp
![image](https://user-images.githubusercontent.com/91208636/147508589-3a125916-1682-4b07-9066-a12ead6cabd0.png)

I started to follow the steps in the introduction. Please let me know if there's something I'm doing wrong

I just edited the following on the python step1_augmentation.py. 

47 num_samples = 1 # because 1 sample data
54 num_augmentations = 20
59 file_name = '/content/drive/MyDrive/tez/Data/labeled-data/labeled-model-UpperJawScan.vtp'.format(i_sample)

output file
![image](https://user-images.githubusercontent.com/91208636/147509402-26ec7e9c-02db-4daf-9fdc-e2ff41d726c1.png)

Then, I just edited the following on the python step2_get_list.py

9 data_path = './augmentation_vtk_data/'
15 num_samples = 1 # because 1 sample data

Then I got this error.  I guess I need to have 6 more labeled datasets right?

Traceback (most recent call last):
  File "step2_get_list.py", line 33, in <module>
    for train_idx, test_idx in kf.split(sample_list):
  File "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py", line 337, in split
    ).format(self.n_splits, n_samples)
ValueError: Cannot have number of splits n_splits=6 greater than the number of samples: n_samples=1.

**Comment by Tai-Hsien** [comment]
We implemented 6-fold cross-validation in step 6. Since you only have one sample, there is no way to conduct 6-fold cross-validation and that's why it says "Cannot have number of splits n_splits=6 greater than the number of samples: n_samples=1".

**Comment by Vaveyla95** [comment]
Hello Tai,

I have labeled dataset Path: /content/drive/MyDrive/tez/meshsegnet/Data/labeled-data
![image](https://user-images.githubusercontent.com/91208636/147788270-c018c383-ca37-4de8-8d23-97091105c3c4.png)

I got error for step1_augmentation.py

num_samples = 7 # need to define # of samples; e.g., 30
vtk_path = '/content/drive/MyDrive/tez/meshsegnet/Data/labeled-data/ # need to define the path; e.g., src

59 file_name = '/content/drive/MyDrive/tez/meshsegnet/Data/labeled-data/Sample_0{0}_d.vtp'.format(i_sample)
60 output_file_name = 'A{0}_Sample_0{1}_d.vtp'.format(i_aug, i_sample)

70 file_name = '/content/drive/MyDrive/tez/meshsegnet/Data/labeled-data/Sample_0{0}_d.vtp'.format(i_sample+1000)
71 output_file_name = 'A{0}_Sample_0{1}_d.vtp'.format(i_aug, i_sample+1000)

Error in load(): cannot load /content/drive/MyDrive/tez/meshsegnet/Data/labeled-data/Sample_01001_d.vtp
Traceback (most recent call last):
  File "step1_augmentation.py", line 76, in <module>
    mesh.applyTransform(vtk_matrix)
AttributeError: 'NoneType' object has no attribute 'applyTransform'

![image](https://user-images.githubusercontent.com/91208636/147788982-caa6eb81-855c-4a2d-a5b7-a8b0c9d7f120.png)

But in the output of the code I have augmentation_vtk_data folder and just for one sample

**Comment by Tai-Hsien** [comment]
You don't have flipped samples. The simplest solution is to comment Line 68-77 in step 1.

**Comment by Vaveyla95** [comment]
https://github.com/Tai-Hsien/MeshSegNet/blob/b2ce6818c31170fa0cfb0951a4574a05613097b2/step1_augmentation.py#L70
It was fixed when file_name = '/content/drive/MyDrive/tez/meshsegnet/Data/labeled-data/Sample_0{0}_d.vtp'.format(i_sample)
i_sample+1000 gives an error

**Comment by Tai-Hsien** [comment]
It caused an error because you don't have a sample with ID of i_sample+1000, which I used for flipped samples. If you plan to conduct an individual project, I recommend you to read all the scripts (at least step1~4) carefully and understand the meaning of each row, instead of just running it.

Hope it helps!

**Comment by Vaveyla95** [comment]
But I have augmentation data in the code output 

A0_sample_01,......, A19-sample_01
A0_sample_02,....., A19-sample_01
.
.
.
A0_sample_01001, ..... , A19_sample_01001
A0_sample_01002, ..... , A19_sample_01002
.
.
.
A0_sample_01007, ..... , A19_sample_01007

**Comment by Tai-Hsien** [comment]
Does your input dataset contain flipped scans? For example, Sample_1001 is the flipped scan of Sample_1. If not, the code was just implemented, but the content might not be right. You can also visualize the augmented data to make sure they are what you expect.

**Comment by Vaveyla95** [comment]
No Sample_01001 file does not exist. Then I don't understand where I am making a mistake. That's all I've done
```
import os
import numpy as np
import vtk
from vedo import *

def GetVTKTransformationMatrix(rotate_X=[-180, 180], rotate_Y=[-180, 180], rotate_Z=[-180, 180],
                               translate_X=[-10, 10], translate_Y=[-10, 10], translate_Z=[-10, 10],
                               scale_X=[0.8, 1.2], scale_Y=[0.8, 1.2], scale_Z=[0.8, 1.2]):
    '''
    get transformation matrix (4*4)
    return: vtkMatrix4x4
    '''
    Trans = vtk.vtkTransform()

    ry_flag = np.random.randint(0,2) #if 0, no rotate
    rx_flag = np.random.randint(0,2) #if 0, no rotate
    rz_flag = np.random.randint(0,2) #if 0, no rotate
    if ry_flag == 1:
        # rotate along Yth axis
        Trans.RotateY(np.random.uniform(rotate_Y[0], rotate_Y[1]))
    if rx_flag == 1:
        # rotate along Xth axis
        Trans.RotateX(np.random.uniform(rotate_X[0], rotate_X[1]))
    if rz_flag == 1:
        # rotate along Zth axis
        Trans.RotateZ(np.random.uniform(rotate_Z[0], rotate_Z[1]))

    trans_flag = np.random.randint(0,2) #if 0, no translate
    if trans_flag == 1:
        Trans.Translate([np.random.uniform(translate_X[0], translate_X[1]),
                         np.random.uniform(translate_Y[0], translate_Y[1]),
                         np.random.uniform(translate_Z[0], translate_Z[1])])

    scale_flag = np.random.randint(0,2)
    if scale_flag == 1:
        Trans.Scale([np.random.uniform(scale_X[0], scale_X[1]),
                     np.random.uniform(scale_Y[0], scale_Y[1]),
                     np.random.uniform(scale_Z[0], scale_Z[1])])

    matrix = Trans.GetMatrix()

    return matrix


if __name__ == "__main__":

    num_samples = 6 # need to define # of samples; e.g., 30
    vtk_path = 'src' # need to define the path; e.g., src
    output_save_path = './augmentation_vtk_data'
    if not os.path.exists(output_save_path):
        os.mkdir(output_save_path)

    sample_list = list(range(1, num_samples+1))
    num_augmentations = 20

    for i_sample in sample_list:
        for i_aug in range(num_augmentations):

            file_name = '/content/drive/MyDrive/tez/meshsegnet/Data/labeled/Sample_0{0}_d.vtp'.format(i_sample)      
            output_file_name = 'A{0}_Sample_0{1}_d.vtp'.format(i_aug,i_sample)
            vtk_matrix = GetVTKTransformationMatrix(rotate_X=[-180, 180], rotate_Y=[-180, 180], rotate_Z=[-180, 180],
                                                  translate_X=[-10, 10], translate_Y=[-10, 10], translate_Z=[-10, 10],
                                                  scale_X=[0.8, 1.2], scale_Y=[0.8, 1.2], scale_Z=[0.8, 1.2]) #use default random setting
            mesh = load(os.path.join(vtk_path, file_name))
            mesh.applyTransform(vtk_matrix)
            io.write(mesh, os.path.join(output_save_path, output_file_name))

        #flipped mesh
        for i_aug in range(num_augmentations):
            file_name = '/content/drive/MyDrive/tez/meshsegnet/Data/labeled/Sample_0{0}_d.vtp'.format(i_sample+1000)
            output_file_name = 'A{0}_Sample_0{1}_d.vtp'.format(i_aug, i_sample+1000)
            vtk_matrix = GetVTKTransformationMatrix(rotate_X=[-180, 180], rotate_Y=[-180, 180], rotate_Z=[-180, 180],
                                                  translate_X=[-10, 10], translate_Y=[-10, 10], translate_Z=[-10, 10],
                                                  scale_X=[0.8, 1.2], scale_Y=[0.8, 1.2], scale_Z=[0.8, 1.2]) #use default random setting
            mesh = load(os.path.join(vtk_path, file_name))
            mesh.applyTransform(vtk_matrix)
            io.write(mesh, os.path.join(output_save_path, output_file_name))
```
and output

❌ Error in load(): cannot load /content/drive/MyDrive/tez/meshsegnet/Data/labeled/Sample_01001_d.vtp
Traceback (most recent call last):
  File "step1_augmentation.py", line 76, in <module>
    mesh.applyTransform(vtk_matrix)
AttributeError: 'NoneType' object has no attribute 'applyTransform'

**Comment by Tai-Hsien** [comment]
As the error message says, "Error in load(): cannot load content/drive/MyDrive/tez/meshsegnet/Data/labeled/Sample_01001_d.vtp". The code cannot load this file because it is not existed (as what you said). The output from `mesh = load(os.path.join(vtk_path, file_name))` become `NoneType`, instead of a VTK object. The attribute function 'applyTransform' can only be used on a VTK object, and that's why the error message says 'NoneType' has no 'applyTransform'.

If you don't have flipped data, it's fine. Just comment Line 68-77 in step 1 and make `with_flip = False` in step 2.

**Comment by Vaveyla95** [comment]
I just labelled 6 unlabeled data in stl format with using the meshlabeler program and saved them in vtp format. These are 
![image](https://user-images.githubusercontent.com/91208636/147827046-0bc9d7d3-e50c-4bb8-822e-1105b5ec6ea6.png)
How should I proceed? My goal is to data augmentation and I want to look at the training and test results of the model
Sorry for my bad experience, i make you tired

**Comment by Vaveyla95** [comment]
If I send you the data, can you send me the test training results of the model?

**Comment by Vaveyla95** [comment]
python step3_training.py 
    
    torch.cuda.set_device(0) # assign which gpu will be used (only linux works)
    use_visdom = False # if you don't use visdom, please set to False
    
    train_list = './train_list_1.csv' # use 1-fold as example
    val_list = './val_list_1.csv' # use 1-fold as example
    model_path = './models/'
    model_name = '/content/drive/MyDrive/tez/meshsegnet/models/MeshSegNet_Max_15_classes_72samples_lr1e-2_best.zip' # need to define

Output is

Training model...
tcmalloc: large alloc 2880004096 bytes == 0x55a06cc7a000 @  0x7f839840fb6b 0x7f839842f379 0x7f828a18ecde 0x7f828a190452 0x7f82dc1b7cf3 0x7f82dc1b8867 0x7f82dc50bcc1 0x7f82dc24d571 0x7f82dc24dda5 0x7f82dc919e52 0x7f82dc7b71db 0x7f82dc256ebb 0x7f82dca0eb02 0x7f82dc4fadfe 0x7f82dc24f769 0x7f82dca0f772 0x7f82dc5bd042 0x7f82ddee86c0 0x7f82ddee8e25 0x7f82dc6123fb 0x7f8385861ab3 0x559e71ecd544 0x559e71ecd240 0x559e71f41627 0x559e71f3bced 0x559e71ecebda 0x559e71f3c915 0x559e71f3bced 0x559e71ecebda 0x559e71f3c915 0x559e71f3bced
tcmalloc: large alloc 2880004096 bytes == 0x55a118710000 @  0x7f839840fb6b 0x7f839842f379 0x7f828a18ecde 0x7f828a190452 0x7f82dc1b7cf3 0x7f82dc1b8867 0x7f82dc50bcc1 0x7f82dc24d571 0x7f82dc24dda5 0x7f82dc919e52 0x7f82dc7b71db 0x7f82dc256ebb 0x7f82dca0eb02 0x7f82dc4fadfe 0x7f82dc24f769 0x7f82dca0f772 0x7f82dc5bd042 0x7f82ddee86c0 0x7f82ddee8e25 0x7f82dc6123fb 0x7f8385861ab3 0x559e71ecd544 0x559e71ecd240 0x559e71f41627 0x559e71f3bced 0x559e71ecebda 0x559e71f3c915 0x559e71f3bced 0x559e71ecebda 0x559e71f3c915 0x559e71f3bced
^C

**Comment by Tai-Hsien** [comment]
> If I send you the data, can you send me the test training results of the model?

We can try that.

**Comment by Vaveyla95** [comment]
[LABEL.zip](https://github.com/Tai-Hsien/MeshSegNet/files/7796576/LABEL.zip)

What's the problem with step 3?

**Comment by Tai-Hsien** [comment]
> [LABEL.zip](https://github.com/Tai-Hsien/MeshSegNet/files/7796576/LABEL.zip)
I checked your data. They already have some rough segmentation result. What do you expect to see?
> 
> What's the problem with step 3?
No idea. Do you have an nvidia GPU to run the training?

**Comment by Vaveyla95** [comment]
I want to get the performance metrics result in step3, step4 and step5 But i got stuck at step3. Can you send me the results for these steps?

**Comment by Vaveyla95** [comment]
No idea. Do you have an nvidia GPU to run the training?

![image](https://user-images.githubusercontent.com/91208636/147836870-a2858298-661a-4422-8daa-df8d9fb3bc19.png)

**Comment by Vaveyla95** [comment]
Can you write me code of downsample for sample_1?

**Comment by Tai-Hsien** [comment]
Hello @Vaveyla95 

First of all, I would like to let you know that I'm willing to discuss and answer questions related to this repo, and provide guidance based on my understanding, but I basically only handle the issue of this repo, instead of basic/advanced python or ML questions.  If you have these questions, you may need to find the answers by yourself. For some of your questions, please see below.

(1) The samples you uploaded are not labeled very well. It doesn't make sense to compare the predicted results to these existing samples for calculating metrics, because they are not good to be ground truth. In addition, to calculate the metrics for your project is not belong to this repo, so I'm sorry that you should try it by yourself.

(2) For downsampling, you should try it by yourself. You can also go to vedo website (https://vedo.embl.es/) to look at examples (https://vedo.embl.es/autodocs/content/vedo/mesh.html?highlight=decimate#vedo.mesh.Mesh.decimate).

(3) Yes, we need to downsample every samples before training (i.e., step 1 to step 3), because current GPU usually doesn't have enough memory to handle original intraoral scans.

Hope this information helps.

**Comment by Vaveyla95** [comment]
You're right, I understand what you mean. I'm trying to do it myself. I'm not experienced as I said,.

I did the downsampling process like this, do you think it looks right?

```
import vedo
from vedo import *

mesh = vedo.load("/content/drive/MyDrive/tez/meshsegnet/Data/labeled/Sample_01.vtp")
output_save_path = '/content/drive/MyDrive/tez/meshsegnet/Data/downlabeled'
output_file_name = 'Sample_01_d.vtp'
if mesh.NCells() > 10000:
                print('\tDownsampling...')
                target_num = 10000
                ratio = target_num/mesh.NCells() # calculate ratio
                mesh_d = mesh.clone()
                mesh_d.decimate(fraction=ratio)
                vedo.io.write(mesh_d,  os.path.join(output_save_path, output_file_name))

```
Then I repeated the steps. Output like this ad step3
```
Training model...
Traceback (most recent call last):
  File "step3_training.py", line 89, in <module>
    for i_batch, batched_sample in enumerate(train_loader):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/drive/MyDrive/tez/meshsegnet/Mesh_dataset.py", line 31, in __getitem__
    labels = mesh.getCellArray('Label').astype('int32').reshape(-1, 1)
AttributeError: 'NoneType' object has no attribute 'astype'
```

**Comment by Tai-Hsien** [comment]
Yes, the label will be deleted when downsampling. When you can do is to project the label array (on original resolution) to the downsampled scans by KNN/SVM. We use the similar way (in step6) to transfer segmentation between different resolutions.

**Comment by Vaveyla95** [comment]
step3

```
Training model...
Traceback (most recent call last):
  File "step3_training.py", line 96, in <module>
    one_hot_labels = nn.functional.one_hot(labels[:, 0, :], num_classes=num_classes)
RuntimeError: Class values must be smaller than num_classes.
```
In some of my samples, the teeth were missing, so there are tooth models with 14 labels instead of 15 labels, I wonder why it gave this error

**Comment by Vaveyla95** [comment]
Here is the part I edited
```
if __name__ == '__main__':

    #torch.cuda.set_device(utils.get_avail_gpu()) # assign which gpu will be used (only linux works)
    use_visdom = False # if you don't use visdom, please set to False

    train_list = './train_list_1.csv' # use 1-fold as example
    val_list = './val_list_1.csv' # use 1-fold as example

    model_path = './models/'
    model_name = 'MeshSegNet_Max_15_classes_72samples_lr1e-2_best.zip' # need to define
    checkpoint_name = 'latest_checkpoint.tar'
```

**Comment by Tai-Hsien** [comment]
What is the maximum label in your all models? If you use Mesh Labeler to prepare your training dataset, you might need to change `num_classes=17` because Mesh Labeler considers wisdom teeth as well. However, if you do that way, then you cannot use our pre-trained model because we trained it using `num_classes=15`.

The easiest solution is to go back to Mesh Labeler to change the labels that not containing wisdom teeth. You can modify the "coloarmap.csv" to delete the wisdom teeth and change the label accordingly.

**Comment by Vaveyla95** [comment]
max label 15 (UL7)

**Comment by Tai-Hsien** [comment]
> max label 15 (UL7) except sample_1. sample_1 is max label 14

Then that's the problem. max label of 15 means it is at least a 16-class problem (0 as background + 15 different objects).

**Comment by Vaveyla95** [comment]
Is missing teeth a problem?

**Comment by Tai-Hsien** [comment]
> ![image](https://user-images.githubusercontent.com/91208636/147857766-9d3d1383-c887-4abc-bacd-fc8a5c7cf484.png) do i have to label teeth like this again?

If you plan to use our pre-trained model, then yes.

**Comment by Vaveyla95** [comment]
I am encountering a memory error
`tcmalloc: large alloc`
What can I do to reduce the memory at step3?

**Comment by Tai-Hsien** [comment]
You can reduce the batch_size for training and validation.
