### ISSUE TITLE
query related teeth_count

### ISSUE THREAD

**Issue by ananyajana** [Tai-Hsien/MeshSegNet#30]
Hi Tai Hsien,

Thank you for your great work.
I have a question regarding the tooth count in the upper jaw/lower jaw. I think fully grown human might have 16 teeth in each jaw. Does it not create problem for the segmentation, I see in the paper that only 14 of the teeth are numbered.
Did you encounter this case where a jaw had 16 teeth and had to pick only 14 out of that as the segmentation is 15 class? Or did you filter out and take only the scans which has 14 teeth in each jaw?

Thanks,
Ananya

**Comment by Tai-Hsien** [comment]
Hello @ananyajana 
There is no problem to change the number of classes to be 16. We set 14 because our datasets only contain 14 teeth. As long as your dataset has models having 16 teeth. You can change the number of classes in step 3 script (i.e., training) and train a network for 16 teeth.

Best,

**Comment by ananyajana** [comment]
Thank you for your quick reply Tai Hsien.
I have another question regarding the mesh decimation.
I used the vedo to decimate the tooth meshes.
I was expecting 10000 points, but I get more than 10k points
Did you face this issue:
this is my code snippet:
  s.decimate(N=10000, method='quadric')
  cnt_aftr = len(s.points())

for different meshes the cnt_aftr varies widely as can be seen from the log below:
cnt_aftr: 10678
cnt_aftr: 10066
cnt_after: 10538
etc

Do you know how to deal with this situation? how to get exactly 10k points?

**Comment by Tai-Hsien** [comment]
Hello,

In my project, I control number of cells instead of points (but you are free to use number of points).
You can see some parts in step 6 (see https://github.com/Tai-Hsien/MeshSegNet/blob/b2ce6818c31170fa0cfb0951a4574a05613097b2/step6_predict_with_post_processing_pygco.py#L71-L75) which is how I did.

The default method for decimate is "quadric", so I believe that's what I used.
