### ISSUE TITLE
A question about step3_training.py

### ISSUE THREAD

**Issue by yacbak** [Tai-Hsien/MeshSegNet#34]
Hello Tai,
Compared to the default patch_size=6000, would meshsegnet perform better if I changed patch_size to 10,000 (the whole downsampling model) or 9,000 or 8,000?
Thank you.

**Comment by Tai-Hsien** [comment]
Hello,
I think so. I tried 9,000 before and got a slightly better results. You can try any number you like to test it.

**Comment by yacbak** [comment]
Thanks for your replying.
