### ISSUE TITLE
I ran step 5 using this model display in the picture bellow. But it looks like the results are completely off. If you would like me to send you the model let me know

### ISSUE THREAD

**Issue by dream3dllc** [Tai-Hsien/MeshSegNet#35]
![image](https://user-images.githubusercontent.com/55261215/156492136-8c33ff54-6608-4c95-b710-2ba556e92bd5.png)

**Comment by Tai-Hsien** [comment]
Your model looks like lower jaw. Which model do you use? maxillary or mandibular? You must select the corresponding one to have a better result.

**Comment by dream3dllc** [comment]
This is the mandibular
![image](https://user-images.githubusercontent.com/55261215/156494667-d931cb12-ec06-48f1-9c9a-8fe1f1a35706.png)

This is the maxillar
![image](https://user-images.githubusercontent.com/55261215/156494721-9e89f419-b970-42f8-8010-ec7a42692ce4.png)

The results looks kind of descent but not that good. What would you recommend so i can get better results. I am new to this, sorry if this is an stupid question

**Comment by Tai-Hsien** [comment]
No worries. I totally agree that they are not good, at least, not good enough. However, it's highly possible since our pre-trained models were trained based on a small dataset, which might be quite different to your dataset.
The way you can improve is to collect your own dataset and train it by your dataset from scratch or conduct a transfer learning based on our pre-train models.

**Comment by dream3dllc** [comment]
Sorry if this sound dumb, what is an transfer learning. It would be good if possible to jump in an chat. I could pay you for your time if that is something you would be ok with. I am new to machine learning in general and trying to understand the system you have in place. I am pretty good with 3D just don't know much about machine learning.

**Comment by Tai-Hsien** [comment]
For transfer learning, you can see https://en.wikipedia.org/wiki/Transfer_learning#:~:text=Transfer%20learning%20(TL)%20is%20a,when%20trying%20to%20recognize%20trucks or some hands-on pytorch example https://pytorch.org/tutorials/beginner/transfer_learning_tutorial.html

**Comment by dream3dllc** [comment]
Hi Tai,
I ran an test using your step 5 learning with your test model that is in your Mesh Labeling software. This is the result i am getting
![image](https://user-images.githubusercontent.com/55261215/156582302-20b2e9e4-7cbb-4c4e-9966-c495b8936dc2.png)

The results still do not look as good either. Would you know why is that the case. The original .vtp file in the github displayed really nicely, but when i manually run the Example-02.stl through the step 5 i get the result above.

**Comment by Tai-Hsien** [comment]
You did everything right. The example in Mesh Labeler repo isn't in our training dataset for MeshSegNet as well, so that' why the result is not that good. However, if you use step6 to predict, which includes the post-processing to refine the result. You can get a better one. I attached the result from step6.

![image](https://user-images.githubusercontent.com/9615481/156608579-4ea403e0-f013-4e4f-9810-068d784b30fa.png)

**Comment by dream3dllc** [comment]
Hi Tai
Using the step 6 gave me some pretty good result that i can work with. There are some models i ran and get this error
Traceback (most recent call last):
  File "step6_predict_with_post_processing_pygco.py", line 133, in <module>
    A_S = np.zeros([X.shape[0], X.shape[0]], dtype='float32')
numpy.core._exceptions.MemoryError: Unable to allocate 297. GiB for an array with shape (282252, 282252) and data type float32

Would you recommend to do an mesh reduction first on the geometry before running that step.

**Comment by dream3dllc** [comment]
Hi Tai-Hsien, It is in C++ but i would not mind sharing it.

**Comment by dream3dllc** [comment]
Hi Tai Hsien,
Looking at your step1_augmentation.py i notices that you are using an seperate index for the flipped mesh. After labeling the mesh in the mesh labeler and export. I only get an single .vtp file. Is the second pass in your step1_augmentation.py the same exact mesh as the base. What is the difference between the flipped .vtp and non flipped .vtp file. Looking at the code i am seeing it just applying random position/rotation/scale.

**Comment by Tai-Hsien** [comment]
It is just a way to augment the dataset since our dataset size is very small. It's similar to an example from vedo (see below).

![image](https://user-images.githubusercontent.com/9615481/158652623-40eb40d4-9544-4bbd-8695-91b215f77259.png)

**Comment by dream3dllc** [comment]
if i do not mirror the data but have enough data to work with, would that be enough.

**Comment by Tai-Hsien** [comment]
Yes, mirror/flipping is only an option.

**Comment by dream3dllc** [comment]
Hi Tai,
I tried to do an test where the model is oriented differently and i get different results. Should i make sure that the models orientation matches the study orientation. Or that should not matter.

**Comment by Tai-Hsien** [comment]
Hello,

It's actually normal. Ideally, the initial orientation should not matter if the model was trained perfectly. However, due to its current limitation, it's still far away from "perfect", so the model still considers the same scan with different orientation as different scans.

**Comment by dream3dllc** [comment]
Hi Tai,
I have a quick question related to the training .tar file you provided. Do you remember specifically how long that training took when you did on the GPU.

**Comment by Tai-Hsien** [comment]
It took quite long to train the model based on the original version. @zheyiLi has modified `Mesh_dataset.py` to speed it up, but I haven't conduct a training with the new code yet.

**Comment by donproc** [comment]
> It took quite long time (at least a few weeks) to train the model based on the original version. @zheyiLi has modified `Mesh_dataset.py` to speed it up, but I haven't conduct a training with the new code yet.

@dream3dllc You may try it and will get different speedup on different platform and sampled mesh size. And you may replace most of  operations in  Mesh_dataset.py with cupy which is compatible with numpy, you will gain further speedup.

One epoch takes around 2500s with 800 training samples and 10000 cells per sample. Validation set is around 100 samples.

**Comment by donproc** [comment]
> Hi Tai, I have a quick question related to the training .tar file you provided. Do you remember specifically how long that training took when you did on the GPU.

1. I tried mixed precision training, but i did not get much speedup
2. I tried set more worker in dataloader, but it did not work because we use gpu in Mesh_dataset.py, you may set torch.multiprocessing.set_start_method('spawn') before training. But it seems not stable
3. I tried dataparallel training, but i did not make it work balance on mutiple gpus because it may need too much extra code changes, finally i just keep the current pattern and optimize the speed of data loading and preprocessing.

**Comment by dream3dllc** [comment]
Hi DonProc/Tai
I really appreciate all the information provided above. If i have any other questions, i will post.

**Comment by donproc** [comment]
> Hi DonProc/Tai I really appreciate all the information provided above. If i have any other questions, i will post. Regarding some of these changes you have made to speed it up. Is that currently on github.

I found the bottleneck is the preprocessing and i put the code of preparing cells and computing adjaciency matrix on github.
I did not put the cupy code on the github.

**Comment by Tai-Hsien** [comment]
offline training increases the speed a lot as well if you have a large dataset.

**Comment by dream3dllc** [comment]
Hi Tai
Before i start the training process for an whole bunch of models. I wanted to know what would be the best way to test one single model to see if the system is doing an pretty good job. For example if i train/validate the system using Model Test2.stl from Mesh_Labeler by augmenting it several time. Then reuse that same model for prediction would it give me the correct result.

**Comment by Tai-Hsien** [comment]
Hello,
You should split your dataset into three sets: training, validation, and test. Depending on the purpose, some people make validation is the same as test, which means at least two sets (training and test).

The subject in the training set should not be used in the test set. If you predict your subject in the training set, the result usually is very good, but it doesn't mean the model is general enough to predict the unseen subject.

**Comment by dream3dllc** [comment]
Hi Tai,
Thanks for answering the above question. Looking at step3_1_continuous_training.py it looks the epoch and other parameters are different than the one used in step3_training. Can you please explain what is the reason behind that.

Thanks

**Comment by Tai-Hsien** [comment]
Hello,
`step3` is used to train from scratch, and `step3_1` is used to keep training parameters based on the previous model. They are actually no difference essentially.

You can change the `num_epochs` by yourself. You need to observe the trend of loss to determine if this training is good enough or not. 200 is just a reason number for us for publish results in the publication. You can train it more if you want.

For the last questions, first, that's actually how "machine learning" works. If you're not familiar with it, I would suggest going for some ML tutorials. During each epoch/iteration, the network parameters will be adjusted based on the loss back propagation.
Second, we actually resample the each mesh in each epoch, so it actually not the exact same mesh.

**Comment by dream3dllc** [comment]
Hello Tai,
I have one last question, in one of the file i had to changed vtk2numpy because i was getting some errors in python that the function did not exist. So i change thos 2 lines:
        points = vtk2numpy(mesh.polydata().GetPoints().GetData())
        ids = vtk2numpy(mesh.polydata().GetPolys().GetData()).reshape((N, -1))[:,1:]

      to
        points = np.array(mesh.polydata().GetPoints().GetData())
        ids = np.array(mesh.polydata().GetPolys().GetData()).reshape((N, -1))[:,1:]

That should be the same thing correct.

**Comment by jeromefabioc** [comment]
So Correct me if i am wrong. If i modify the code to use the entire 10k polygon instead of 6k polygons. I would not need to Augment each individual mesh. I could just use 1 single ground truth mesh and train of that.

**Comment by jeromefabioc** [comment]
> Hello, We did this way to "create" more subject since our dataset was very small. a 10k polygons can "generate" many different "6k" polygon. If you use all 10k polygons, then you only have one subject in your training. This is just some resampling skill.

I think i understand what you mean. Because you are resampling the data multiple time, so the 6k polygons will be different everytime given you an new set to train from. But that still does not guarantee that you will have all the train information for all the label informations

**Comment by jeromefabioc** [comment]
Yes in in code in this repo i can see that in step1 you do the transformed augmentation. Then in step 3 when you train i can see where you are sample 6k from the 10k polygons. I just wanted to know if i end up not augmenting my files in the step 1 and just use the ground truth model directly in step3 and modify it to use the entire 10k polygon and train from that. I have enough models i can feed the system, would that create an overfitting problem.

**Comment by Tai-Hsien** [comment]
It's hard to say. You need to monitor the training and validation curve to see if it's overfitting or not.

**Comment by jeromefabioc** [comment]
> It's hard to say. You need to monitor the training and validation curve to see if it's overfitting or not. You can always try the thing you like. It won't harm anything.

Thanks, i really appreciate it. I will try it and let you know what i found.

**Comment by jeromefabioc** [comment]
Hi Tai, 
I have a quick question. The current Model for upper and lower are from the second molar to the second molar. I notice that it is labeling the second molar as 1 from the right and the second molar on the left as 14. So what i was thinking of instead of having to do an learning from scratch, i want to do an continuous learning that would include the first molars which in that case i would need to change the num_channels or num_classes to 17 in order to account for the two additional teeth. I know all the learning was done with the labels set 1 and 14 for the second molars. So what i was thinking is maybe i can assign an label of 15 and 16 for the first two molars. That way it won't affect the current training. Then i would use step3_continuous learning to learn models with first molars. Does that make any sense or am i completely off

**Comment by Tai-Hsien** [comment]
Yes, it's okay if you labeled additional teeth followed by the existing numbers.
