### ISSUE TITLE
There is no latest checkpoint.tar to continue training

### ISSUE THREAD

**Issue by s-triar** [Tai-Hsien/MeshSegNet#37]
Hi, I want to continue the training using the data I acquired. But the `step3_1_continous_training.py` file mentions `lastest_checkpoint.tar` where the model is loaded from. How do I continue the training using my data? 

thanks for the great work and help

**Comment by Tai-Hsien** [comment]
You can just change `latest_checkpoint.tar` in `step3_1` to the pre-trained model that we uploaded.

**Comment by s-triar** [comment]
Thanks for the response, I have to tweak the `step2_get_list.py` because my dataset is only 2 right now.

I successfully load the pre-trained model. however, I got the error
```
one_hot_labels = nn.functional.one_hot(labels[:, 0, :], num_classes=num_classes)
RuntimeError: Class values must be smaller than num_classes
```

After searching on the issue in [1](https://github.com/Tai-Hsien/MeshSegNet/issues/29#issuecomment-1003593388) I found that the label in MeshLabeler includes the background and your model uses 15 labels (classes). So I can not continue training your model because I labeled using MeshLabeler with 14 teeth and 1 gingiva.

On the contrary, on this [2](https://github.com/Tai-Hsien/MeshSegNet/issues/17#issuecomment-878051033),  I wonder why you suggested, `num_classes=17` instead of 18 because of the background?

**Comment by Tai-Hsien** [comment]
Hello,
(1) dataset size of 2 is too small to train a model. You might need to gather more samples first.
(2) The way to label in Mesh_Labeler cannot be directly used in this repo. In this repo, we defined 15 classes (14 teeth + background) at the beginning since our dataset didn't include wisdom teeth at that time. However, Mesh_Labeler considers wisdom teeth, so we added two additional labels for wisdom teeth and end up 17 classes (i.e., 16 teeth + 1 background each arch).
(3) It's up to your design, if you 15-class is good for you, you can use our pre-trained model and modified colormap.csv in Mesh_Labeler by yourself for the 15-class problem. If you plan to do 17-class, then there is no pre-trained model available in this repo.

**Comment by s-triar** [comment]
Thanks for the response.
(1) I am labeling and only 2 Maximilar have been done so far with 14 teeth. So I can debug while continuing the labeling process
(2) Changing num_classes to 16 is working.
(3) regarding the num_channels issue. I got these errors in these cases (value)

`num_channels=14` Got error below
`RuntimeError: Given groups=1, weight of size [64, 14, 1], expected input[6, 15, 6000] to have 14 channels, but got 15 channels instead`

`num_channels=15` Got the error below
```
  File "d:MeshSegNet-master\MeshSegNet-master\losses_and_metrics_for_mesh.py", line 103, in Generalized_Dice_Loss
    w = class_weights[c]/class_weights.sum()
IndexError: index 15 is out of bounds for dimension 0 with size 15
```

`num_channels=16` Got the error below
`RuntimeError: Given groups=1, weight of size [64, 16, 1], expected input[6, 15, 6000] to have 16 channels, but got 15 channels instead`

**Comment by Tai-Hsien** [comment]
(1) `num_channels` is not equal to `num_classes`. Number of channels mean cell XYZ positions and normal vectors. If you didn't change the input structure, it should be 15.
I further check the code in repo, if you change `num_classes`, you also need to modify Line 76 as follows.
`class_weights = torch.ones(num_classes).to(device, dtype=torch.float)`

(2) `num_classes=16` works doesn't mean it makes sense. You need to think about what it mean.

**Comment by s-triar** [comment]
Thanks for the information.

I assume the Mesh_Labeler implicitly includes 2 wisdom teeth and they are not counted in the VTP file. So the number of classes I should set is 17 (14 teeth+1 gingiva+2 wisdom teeth. I am rather confused with the `background` you mention. is it the background which is white or gingiva?

**Comment by Tai-Hsien** [comment]
Yes, the way you label the data should be general across the entire dataset. The example having max_label of 15 was just one subject, so `num_classes` should be 17 which makes more sense.

I define the background here is non-tooth area (i.e., gingiva in my dataset), which is the way I label my dataset.

**Comment by s-triar** [comment]
Thanks for your help. The training is running already.

**Comment by s-triar** [comment]
> Thanks for the response. (1) I am labeling and only 2 Maximilar have been done so far with 14 teeth. So I can debug while continuing the labeling process (2) Changing num_classes to 16 is working. (3) regarding the num_channels issue. I got these errors in these cases (value)
> 
> `num_channels=14` Got error below `RuntimeError: Given groups=1, weight of size [64, 14, 1], expected input[6, 15, 6000] to have 14 channels, but got 15 channels instead`
> 
> `num_channels=15` Got the error below
> 
> ```
>   File "d:MeshSegNet-master\MeshSegNet-master\losses_and_metrics_for_mesh.py", line 103, in Generalized_Dice_Loss
>     w = class_weights[c]/class_weights.sum()
> IndexError: index 15 is out of bounds for dimension 0 with size 15
> ```
> 
> `num_channels=16` Got the error below `RuntimeError: Given groups=1, weight of size [64, 16, 1], expected input[6, 15, 6000] to have 16 channels, but got 15 channels instead`
> 
> and here the labels in my VTP ![image](https://user-images.githubusercontent.com/34316314/159700909-4d8b0d4f-c010-4c0e-bb19-0d2abb9736b3.png)


Hi, 
I have read your paper DOI: [10.1109/TMI.2020.2971730](https://doi.org/10.1109/TMI.2020.2971730).
In bab III. Materials and Method and section A. Data and Pre-Processing, you stated that you used 15 classes (from central incisor to the second molar on bot right and left) and you denoted them as UR1-UR7 and UL1-UL7 if it were Maxillary.

 As for my case, it is the same. I labeled 15 classes like what you did. 
When I debug your program using my data, I found that the label I used is like this
`0  2  3  4  5  6  7  8  9 10 11 12 13 14 15`
and that is the cause for the error when I set `num_classes=15`.
It happened because the label list in Mesh Labeler is like the image below
![image](https://user-images.githubusercontent.com/34316314/160274492-4fe486d7-0dda-41ff-967f-b1dc40aafe59.png)

I want to ask, did you start the UR7/LL7 to be label number 1? and is the color afect the result?

**Comment by Tai-Hsien** [comment]
Hello,
Yes, in our previous publication, we labeled UR7 as 1, UR6 as 2, and so on.
As I mentioned before, the ways to label subjects are different in Mesh Labler and in our previous publication.
However, you can define the way to label (colormap.csv) in Mesh Labeler to what you want, such as the way UR7 as 1, etc.)
