### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'astype'

### ISSUE THREAD

**Issue by elias-Mimetrik** [Tai-Hsien/MeshSegNet#38]
Hello,

I'm getting the following error when running `step3_training.py`. It happens on this line:
```labels = mesh.getCellArray('Label').astype('int32').reshape(-1, 1)```
I have checked that `mesh` is loaded correctly, however the result of `mesh.getCellArray('Label')` is `None`. The version of vedo I'm using is the same as the one used in this repo `vedo==2020.4.2`.

```
Traceback (most recent call last):
  File "step3_training.py", line 89, in <module>
    for i_batch, batched_sample in enumerate(train_loader):
  File "/home/elias/miniconda3/envs/TSeg/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/elias/miniconda3/envs/TSeg/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 403, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/elias/miniconda3/envs/TSeg/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/elias/miniconda3/envs/TSeg/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/elias/eclipse-workspace/itnet-infer/06_downsample_pcl/MeshSegNet/Mesh_dataset.py", line 39, in __getitem__
    labels = mesh.getCellArray('Label').astype('int32').reshape(-1, 1)
AttributeError: 'NoneType' object has no attribute 'astype'
```

Any ideas please?

**Comment by Tai-Hsien** [comment]
In your dataset, your subjects don't contain a cell array named 'Label'. You can change the name of cell array to the right one in your dataset.

**Comment by Tai-Hsien** [comment]
In vedo, you can create a cell array to store your label, and you can define the name of the array. For example, I call the array as 'Label'. Do you already have the label on your dataset? If so, what is the way you save them?

**Comment by elias-Mimetrik** [comment]
Each vertex of a training data object has an rgb colour, the labels aren't saved outside of the mesh..

**Comment by Tai-Hsien** [comment]
> Can you please point me to the vedo function which can add the Labels property to the VTP files?
E.g.,
mesh.addCellArray(np_array, ], dtype=np.int32), array_name)

**Comment by elias-Mimetrik** [comment]
Thanks very much.

My meshes are **.ply** files. But I convert them to **.vtp** files before I do the augmentation step. I will need to add the labels to them first. If I am not wrong, the size of this array will be equal to the size of the vertices.

Very strange, it looks like _addCellArray_ function is not documented in vedo. The closest function I could find is:
https://vedo.embl.es/autodocs/content/vedo/mesh.html#vedo.mesh.Mesh.addCellArea

**Comment by elias-Mimetrik** [comment]
Thanks very much.
