### ISSUE TITLE
how can I downsample/simplify the raw mesh then label also changes

### ISSUE THREAD

**Issue by zhDai** [Tai-Hsien/MeshSegNet#4]
hi, I have labeled  on the raw mesh, so how can I downsample/simplify the raw mesh then label also changes.

**Comment by Tai-Hsien** [comment]
Hello zhDai,

The way I suggest is to train a SVM model for the downsampled label. You can use your raw mesh and label as training data to train the SVM model, and use the dwonsampled mesh as unseen data for prediction of downsampled label. Let me know if you need more help for this implementation.

**Comment by zhDai** [comment]
> Hello zhDai,
> 
> The way I suggest is to train a SVM ork KNN model for the downsampled label. You can use your raw mesh and label as training data to train the model, and use the dwonsampled mesh as unseen data for prediction of downsampled label. Let me know if you need more help for this implementation.

thanks for your reply。I have done this。the outcomes make me refine the boundary which between teeth and gingiva。appreciate for your work。

**Comment by Tai-Hsien** [comment]
Hello ZhDai,
You are right, but that's the way I only currently. If you're using VTK (specifically, VTP) with a cell array named "Label", you might use the GUI program (https://github.com/Tai-Hsien/Mesh_Labeler) I developed to modify the boundary.

**Comment by zhDai** [comment]
> Hello ZhDai,
> You are right, but that's the way I only currently. If you're using VTK (specifically, VTP) with a cell array named "Label", you might use the GUI program (https://github.com/Tai-Hsien/Mesh_Labeler) I developed to modify the boundary.

yeah~thanks
