### ISSUE TITLE
Mesh-based methods or point-based methods?

### ISSUE THREAD

**Issue by yifliu3** [Tai-Hsien/MeshSegNet#48]
Hi, thanks for your great work.
I'm wondering if mesh-based works perform better than point-based methods since mesh-based methods seem to provide more topology information, but point-based methods looks more flexible as it is permutation invariant.

**Comment by Tai-Hsien** [comment]
Hello,
I agree what you said right now.
According to our work in IEEE TMI 2020 paper, the "additional" information from mesh can provide a better result.
However, It's a good and big question, and I believe the answer depends on the network structure. It needs more investigation.
Maybe you can look at some latest papers regarding this.

**Comment by yifliu3** [comment]
Thanks for your reply, and I will check more papers.
