### ISSUE TITLE
for step6

### ISSUE THREAD

**Issue by zhDai** [Tai-Hsien/MeshSegNet#5]
hello， when I do the scripts like 'python step6_predict_with_post_processing.py'.the error will happen like this：
Predicting Sample filename: 41159604_shell_teethup_l.stl
	Downsampling...
	Predicting...
	Refining...
Invalid MEX-file '/data/dl/daizh/MeshSegNet/bin/gco_matlab.mexa64': 
Missing symbol '_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERmm' required by '/data/dl/daizh/MeshSegNet/bin/gco_matlab.mexa64'.

can you help me？

**Comment by Tai-Hsien** [comment]
Hello zhDai,

It looks like there has some file missing. It's a little bit hard to debug for your personal environment. Have you installed MATLAB and the corresponding engine for python?

What I really suggest is to install pygco (https://github.com/amueller/gco_python) which is the python version of gco.
Once you have done this, please let me know and I can share the step6 script based on pygco.

**Comment by zhDai** [comment]
> Hello zhDai,
> 
> It looks like there has some file missing. It's a little bit hard to debug for your personal environment. Have you installed MATLAB and the corresponding engine for python?
> 
> I have updated step6 scripts and added one based on pygco (https://github.com/amueller/gco_python). Pygco is the python version of gco. The pygco version is little bit faster and use less memory. Please see "step6_predict_with_post_processing_pygco.py".

I have installed MATLAB and the corresponding engine for python。emm~then， I will try "step6_predict_with_post_processing_pygco.py" and show you the outcome as soon as fast.Thanks for your reply.

**Comment by zhDai** [comment]
> Hello zhDai,
> 
> It looks like there has some file missing. It's a little bit hard to debug for your personal environment. Have you installed MATLAB and the corresponding engine for python?
> 
> I have updated step6 scripts and added one based on pygco (https://github.com/amueller/gco_python). Pygco is the python version of gco. The pygco version is little bit faster and use less memory. Please see "step6_predict_with_post_processing_pygco.py".

I can do this，thanks~
