### ISSUE TITLE
about the distance_matrix and the threshold  after without normalization of 'X' in line 70 of Mesh_dataset.py

### ISSUE THREAD

**Issue by huizhang2017** [Tai-Hsien/MeshSegNet#9]
Hi, Tai-Hsien,
     I have a question about the threshold of D in line 104. Because normalization is redundant in line 70. So I think the threshold of 0.1 and 0.2 in line 104 and 107 should also change. According to my estimation, they should be set to about 0.025 and 0.05.  Is that right?

**Comment by Tai-Hsien** [comment]
Hello,

Line 70 is commented out in the current version. The meaning of thresholds in Lines 104 and 107 is something like the receptive field for the neighbor features. It's flexible and the best threshold varies depending on the task. It is just empirical to set 0.1 and 0.2. Feel free to change it and see if the results are better.

**Comment by huizhang2017** [comment]
I see, Thanks. But if I still set 0.1 and 0.2, then, I think S1 and S2 is not the sparse matrix.

**Comment by Tai-Hsien** [comment]
If the threshold is too large, it might not be sparse matrixes. However, it should still work.
